name: go-crossbuild
  uses: izumin5210/action-go-crossbuild@v1.0.0
  with:
    # An application name
    name: # optional, default is 
    # Space or comma separated list of GOARCH
    arch: # optional, default is amd64
    # Path to destination directory of built binaries
    dest: # optional, default is ./dist
    # `-ldflags` to pass to go build
    ldflags: # optional, default is 
    # `-tags` to pass to go build
    tags: # optional, default is 
    # Space or comma separated list of GOOS
    os: # optional, default is darwin,linux,windows
    # Build target package
    package: # optional, default is .
    # Version of github.com/Songmu/goxz
    goxz-version: # optional, default is v0.4.1
